{"name": "test_loginError[udata0]", "status": "passed", "parameters": [{"name": "udata", "value": "{'longtransportid': 1093, 'username': 'syx9220', 'password': 123456}"}], "start": 1660213716882, "stop": 1660213717290, "uuid": "6934af69-d1ee-498b-87a9-262beacf9bd4", "historyId": "47ea4e34bbf082a7c68fcbe9a27e34b2", "testCaseId": "d71a2910c5a241c986cecb1081c4532c", "fullName": "py_test.TestCase#test_loginError", "labels": [{"name": "tag", "value": "@pytest.mark.filterwarnings('ignore::UserWarning')"}, {"name": "suite", "value": "py_test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "xiaocaodeMac.local"}, {"name": "thread", "value": "5438-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_test"}]}